[package]
name = "h5"
version = "1.0.0"
authors = []

[addresses]
#basic_address = "0xa19a0ee429b5311629be59c030574e43ae7be8dd55a098e7475dd0fb8dd4e214"
basic_address = "0xb5bd399904c677df089612da6513835cd46f2512923ff870b68cebf27bda66d8"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
